@URL = http://localhost:8080/api
@USERNAME = admin
@PASSWORD = 123456


###

POST {{URL}}/login HTTP/1.1
Body:

{
  "loginUsername": "{{USERNAME}}",
  "loginPassword": "{{PASSWORD}}"
}

###

GET {{URL}}/messages HTTP/1.1

###

POST {{URL}}/messages HTTP/1.1
Body:

{
  "messageText": "Hello, world!",
  "messageReplyId": 1
}

###

GET {{URL}}/users HTTP/1.1

###

GET {{URL}}/meta HTTP/1.1
