name: Build & Upload Artifacts

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v4
        with:
          just-version: "1.40"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup PureScript
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          spago: "latest"

      - name: Install elm
        run: |
          bun add -g elm
          elm --version

      - name: Install Idris2 & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chezscheme
          echo "chezscheme" | bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"
          echo "$HOME/.pack/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      - name: Install npm dependencies
        run: |
          bun install
          cd client && bun install

      - name: Run just build
        run: |
          just gen
          just build
          just test

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: client/dist
          retention-days: 30
          if-no-files-found: warn

      - name: Upload Backend Build
        uses: actions/upload-artifact@v4
        with:
          name: backend-output
          path: server/output
          retention-days: 30
          if-no-files-found: warn

      - name: Upload Database Build
        uses: actions/upload-artifact@v4
        with:
          name: db-build
          path: db
          retention-days: 30
          if-no-files-found: warn

      - name: Upload All Artifacts (Combined)
        uses: actions/upload-artifact@v4
        with:
          name: full-build-artifacts
          path: |
            client/dist/
            server/output/
            db/
          retention-days: 30
          if-no-files-found: warn
